markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - vespaapps_index.json

include:
  - .github/

defaults:
  -
    scope:
      path  : ""
    values:
      index : true

search:
  namespace: "vespaapps"
  doc_type: "doc"
  do_feed  : true
  do_index_removal_before_feed: false
  feed_endpoints:
    # This config needs to be the same in all files starting with "_" in:
    # vespa-engine/documentation, vespa-engine/pyvespa, vespa-engine/sample-apps,
    # vespaai/blog and vespaai/cloud-site
    #
    # vespacloud-docsearch | prod.aws-us-east-1c
    - url: https://b671e1db.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - vespaapps_index.json
    # vespacloud-docsearch | prod.aws-eu-west-1a
    - url: https://ed053d52.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - vespaapps_index.json
    # vespacloud-docsearch | prod.gcp-us-central1-f
    - url: https://a341952a.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - vespaapps_index.json
    # vespacloud-docsearch | prod.gcp-us-central1-a
    - url: https://ba97230a.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - vespaapps_index.json
    # vespacloud-docsearch.cloud-enclave | prod.aws-us-east-1c
    - url: https://cd560c23.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - vespaapps_index.json
    # vespacloud-docsearch.cloud-enclave | prod.aws-eu-west-1a
    - url: https://b24dd625.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - vespaapps_index.json
    # vespacloud-docsearch.cloud-enclave | prod.gcp-us-central1-f
    - url: https://ab1f72fd.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - vespaapps_index.json
