# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

search:
  namespace: "vespaapps-p"
  doc_type: "term"
  do_feed  : true
  do_index_removal_before_feed: false
  feed_endpoints:
    # vespacloud-docsearch // aws // us-east-1c
    - url: https://b671e1db.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - suggestions_index.json
    # vespacloud-docsearch // gcp // us-central1-f
    - url: https://a341952a.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - suggestions_index.json
    # vespacloud-docsearch // aws // eu-west-1a
    - url: https://ed053d52.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - suggestions_index.json
    # vespacloud-docsearch // aws (enclave) // us-west-1c
    - url: https://f10d3607.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - suggestions_index.json
    # vespacloud-docsearch // gcp (enclave) // us-central1-f
    - url: https://ac5f3559.b68a8c0d.z.vespa-app.cloud/
      indexes:
        - suggestions_index.json
