# Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
version: '3.7'
services:
  config0:
    image: vespaengine/vespa
    hostname: "config0-vespa-net"
    environment:
      - VESPA_TLS_CONFIG_FILE=/var/tls/tls.json
      - VESPA_CONFIGSERVERS=config0-vespa-net,config1-vespa-net,config2-vespa-net
    ports:
      - target: 5005
        published: 5005
        mode: host
      - target: 19071
        published: 19071
        mode: host
    networks:
      net:
        ipv4_address: 10.0.10.10
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs
      - type: bind
        source: ./tls
        target: /var/tls

  config1:
    image: vespaengine/vespa
    hostname: "config1-vespa-net"
    environment:
      - VESPA_TLS_CONFIG_FILE=/var/tls/tls.json
      - VESPA_CONFIGSERVERS=config0-vespa-net,config1-vespa-net,config2-vespa-net
    networks:
      net:
       ipv4_address: 10.0.10.11
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs
      - type: bind
        source: ./tls
        target: /var/tls

  config2:
    image: vespaengine/vespa
    hostname: "config2-vespa-net"
    environment:
      - VESPA_TLS_CONFIG_FILE=/var/tls/tls.json
      - VESPA_CONFIGSERVERS=config0-vespa-net,config1-vespa-net,config2-vespa-net
    networks:
      net:
        ipv4_address: 10.0.10.12
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs
      - type: bind
        source: ./tls
        target: /var/tls

  container0:
    image: vespaengine/vespa
    command: services
    hostname: "container0-vespa-net"
    environment:
      - VESPA_TLS_CONFIG_FILE=/var/tls/tls.json
      - VESPA_CONFIGSERVERS=config0-vespa-net,config1-vespa-net,config2-vespa-net
    ports:
      - target: 8080
        published: 8080
        mode: host
      - target: 8443
        published: 8443
        mode: host
    networks:
      net:
        ipv4_address: 10.0.10.13
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs
      - type: bind
        source: ./tls
        target: /var/tls

  container1:
    image: vespaengine/vespa
    command: services
    hostname: "container1-vespa-net"
    environment:
      - VESPA_TLS_CONFIG_FILE=/var/tls/tls.json
      - VESPA_CONFIGSERVERS=config0-vespa-net,config1-vespa-net,config2-vespa-net
    ports:
      - target: 8080
        published: 8081
        mode: host
    networks:
      net:
        ipv4_address: 10.0.10.14
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs
      - type: bind
        source: ./tls
        target: /var/tls

  container2:
    image: vespaengine/vespa
    command: services
    hostname: "container2-vespa-net"
    environment:
      - VESPA_TLS_CONFIG_FILE=/var/tls/tls.json
      - VESPA_CONFIGSERVERS=config0-vespa-net,config1-vespa-net,config2-vespa-net
    ports:
      - target: 8080
        published: 8082
        mode: host
    networks:
      net:
        ipv4_address: 10.0.10.15
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs
      - type: bind
        source: ./tls
        target: /var/tls

  content0:
    image: vespaengine/vespa
    command: services
    hostname: "content0-vespa-net"
    environment:
      - VESPA_TLS_CONFIG_FILE=/var/tls/tls.json
      - VESPA_CONFIGSERVERS=config0-vespa-net,config1-vespa-net,config2-vespa-net
    networks:
      net:
        ipv4_address: 10.0.10.16
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs
      - type: bind
        source: ./tls
        target: /var/tls

  content1:
    image: vespaengine/vespa
    command: services
    hostname: "content1-vespa-net"
    environment:
      - VESPA_TLS_CONFIG_FILE=/var/tls/tls.json
      - VESPA_CONFIGSERVERS=config0-vespa-net,config1-vespa-net,config2-vespa-net
    networks:
      net:
        ipv4_address: 10.0.10.17
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs
      - type: bind
        source: ./tls
        target: /var/tls

  content2:
    image: vespaengine/vespa
    command: services
    hostname: "content2-vespa-net"
    environment:
      - VESPA_TLS_CONFIG_FILE=/var/tls/tls.json
      - VESPA_CONFIGSERVERS=config0-vespa-net,config1-vespa-net,config2-vespa-net
    networks:
      net:
        ipv4_address: 10.0.10.18
    volumes:
      - data:/opt/vespa/var
      - logs:/opt/vespa/logs
      - type: bind
        source: ./tls
        target: /var/tls

volumes:
  data:
    external: true
    name: '{{.Service.Name}}-{{.Task.Slot}}-data'

  logs:
    external: true
    name: '{{.Service.Name}}-{{.Task.Slot}}-logs'
  
networks:
  net:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/24
